// USER
export const SET_USERDATA = 'SET_USERDATA'
export const SET_USER_LOADING = 'SET_USER_LOADING'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'


// PEOPLELIST
export const PEOPLELIST_SET_LOADING = 'PEOPLELIST_SET_LOADING'
export const PEOPLELIST_SET_SEARCHLIST = 'PEOPLELIST_SET_SEARCHLIST'
export const PEOPLELIST_SET_FRIENDLIST = 'PEOPLELIST_SET_FRIENDLIST'
export const PEOPLELIST_ADD_FRIEND = 'PEOPLELIST_ADD_FRIEND'
export const PEOPLELIST_REMOVE_FRIEND = 'PEOPLELIST_REMOVE_FRIEND'
export const PEOPLELIST_SET_USERINFO = 'PEOPLELIST_SET_USERINFO'
export const PEOPLELIST_ADD_REQUEST = 'PEOPLELIST_ADD_REQUEST'
export const PEOPLELIST_REMOVE_REQUEST = 'PEOPLELIST_REMOVE_REQUEST'
export const PEOPLELIST_ADD_INVITE = 'PEOPLELIST_ADD_INVITE'
export const PEOPLELIST_REMOVE_INVITE = 'PEOPLELIST_REMOVE_INVITE'
export const PEOPLELIST_SET_FRENDISONLINE = 'PEOPLELIST_SET_FRENDISONLINE'
export const PEOPLELIST_SET_FRENDISMESSAGE = 'PEOPLELIST_SET_FRENDISMESSAGE'


// CHAT
export const CHAT_SET_MESSAGES = 'CHAT_SET_MESSAGES'
export const CHAT_SET_LOADING = 'CHAT_SET_LOADING'
export const CHAT_ADD_MESSAGE = 'CHAT_ADD_MESSAGE'
export const CHAT_REQUEST_MESSAGE = 'CHAT_REQUEST_MESSAGE'
export const CHAT_SET_INITSTATUS = 'CHAT_SET_INITSTATUS'